[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicy = "on-failure"
maxRestartCount = 3

[service]
tcp_proxy_port = 8000
healthcheck_path = "/"
healthcheck_timeout = 5
healthcheck_interval = 30
