"""Initial schema

Revision ID: 2b96bec0820a
Revises: 
Create Date: 2026-03-07 02:05:36.545566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b96bec0820a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('market_slug', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('outcome_win', sa.Integer(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kv',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kv')
    op.drop_table('closed_trades')
    # ### end Alembic commands ###
